name: kashmeer_milk
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  file_picker: ^9.2.1
  csv: ^6.0.0
  http: ^1.3.0
  firebase_storage: ^12.4.1
  cloud_firestore: ^5.6.2
  permission_handler: ^11.4.0
  excel: ^4.0.6
  url_launcher: ^6.3.1
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.3
  path_provider: ^2.1.5
  uuid: ^4.5.1
  fluttertoast: ^8.2.12
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.17
  share_plus: ^10.1.4
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_sms: ^2.3.3
  table_calendar: ^3.0.9
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
flutter:
  uses-material-design: true

  assets:
    - assets/splash.png
    - assets/login.png
    - assets/profile.png
    - assets/ahmad.png
    - assets/mask.png
    - assets/bg.png
    - assets/image.png
    - assets/food.svg
    - assets/home.svg
    - assets/pay.svg
    - assets/profile.svg
    - assets/speed.svg
