name: kashmeer_milk
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  file_picker: ^8.3.1
  csv: ^6.0.0
  http: ^1.3.0
  firebase_storage: ^12.4.1
  cloud_firestore: ^5.6.2
  permission_handler: ^11.3.1
  excel: ^4.0.6
  url_launcher: ^6.3.1
  provider: ^6.1.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash.png
    - assets/login.png
    - assets/profile.png
    - assets/ahmad.png
    - assets/mask.png
    - assets/bg.png
